### ISSUE TITLE
variable names and underscores

### ISSUE THREAD

**Issue by mauro3** [JuliaPraxis/Naming#2]
I think the convention is Julia is to avoid underscore unless the variable name really becomes unreadable.  For example `get...`:

```
get                    getaddrinfo             getkey
get!                   getfield                getpid
get_bigfloat_precision gethostname             getsockname
get_rounding           getindex
get_zero_subnormals    getipaddr
```

As it stands you would recommend to use `_` for most of them.

**Comment by JeffreySarnoff** [comment]
Inadvertently, I may have dropped the note that says precisely what you suggest.  The guidance should be (generally) to drop the underscore with short words/forms. Phrased right, this would reproduce your list.

**Comment by JeffreySarnoff** [comment]
Revised:
[Functions](https://github.com/JuliaPraxis/Naming/blob/master/guides/Functions.md)
[Variables](https://github.com/JuliaPraxis/Naming/blob/master/guides/Variables.md)
