### ISSUE TITLE
A question about acronym 

### ISSUE THREAD

**Issue by AStupidBear** [JuliaPraxis/Naming#4]
Can you explain why ```For package, module or type names with an initial acronym
write the acronym in uppercase then use camelcase```.

**Comment by mkborregaard** [comment]
`CSSStyles` rather than `CssStyles` or `CSSstyles`. This has been the topic of considerable debate.

**Comment by Ismael-VC** [comment]
I prefer `CSS_Styles`.

**Comment by mkborregaard** [comment]
Muarhaha. So many possibilities.

**Comment by Ismael-VC** [comment]
Specialy for compound acronyms like: `AWS_EC2` instead of `AWSEC2`, `AWS_IAM` instead of `AWSIAM` and so on for `AWS_S3`, `AWS_SDB`, `AWS_SES`, `AWS_SNS`, etc. All of these are real Julia packages with hard names to read, I think sprinkling a few `_` would here and there would be nice.

**Comment by Ismael-VC** [comment]
`_`s are not 👿  IMHO! 😄

**Comment by nalimilan** [comment]
The Julia manual does not recommend/allow underscores in package names.

**Comment by AStupidBear** [comment]
I prefer CssStyles. Anyway, I dislike ```CSSstyles``` for its visual inconsistency.

**Comment by mkborregaard** [comment]
Almost everyone prefers CssStyles, as came out the last time this was (extensively) discussed. There was even a gitter chatroom called "I prefer CssStyles". But in the end it was thought to go against the naming guidelines in julia's documentation - hence the phrasing you found in your original question.

**Comment by gabrielgellner** [comment]
Wait ... it seems that the guide actually uses `CSSstyles` not the `CSSStyles` I thought was the consensus. Did I miss something?

**Comment by JeffreySarnoff** [comment]
No, you did not miss anything.  You caught something good. I could not stomach CSSStyles.

**Comment by JeffreySarnoff** [comment]
No, you did not miss anything. You caught something good. I could not stomach CSSStyles.

The majority of input was to greatly prefer CSSstyles to CSSStyles.  This is the only place where the Praxis shifts from the manual -- the intent is to move the manual.  Either way -- I thought it important that the more readable way was sanctioned somewhere.

The problem with CssStyles is not about appearance -- it is about the stricture to use all caps for Acronyms -- I did not want to violate that in the Praxis: consider HTMLWidgetCollection vs HtmlWidgetCollection.

I would be more than pleased if the manual recommended either CssStyles or CSSstyles over CSSStyles.  CssStyles is more flexible as the pattern works with three-word package names.

**Comment by JeffreySarnoff** [comment]
The problem with CssStyles is not about appearance -- it is about the stricture to use all caps for Acryonyms -- I did not want to violate that in the Praxis.

**Comment by gabrielgellner** [comment]
Okay I guess this can be closed. I personally can not stomach `CSSstyles`, I really hate special cases, but maybe this will catch on, I was just surprised when I noticed what @mkborregaard was not reflected in the Praxis. Hurts me a bit that my own style will not be fully Praxis compliant! I will use `CSSStyles` and no vertical alignment with spacing. Might need to have some kind of "I am compliant at Praxis level 1" ;)

**Comment by JeffreySarnoff** [comment]
What is your ideal version of CSS Styles?

**Comment by gabrielgellner** [comment]
Sorry, my ideal, like @mkborregaard mentioned is `CssStyles`, but I feel that that goes way against what has already happened in the julia ecosystem, and Base. So practically I then prefer `CSSStyles`.

**Comment by JeffreySarnoff** [comment]
Oh .. yes .. I prefer CssStyles too.  Maybe I was too deferential before.  
@mkborregaard What do you think of acknowledging the manual's preference and providing along with that a note for the "community preference" ?

**Comment by JeffreySarnoff** [comment]
@gabrielgellner your thought?

**Comment by JeffreySarnoff** [comment]
OK -- after careful review, and a desire that there be no need to revisit this -- I swapped the :OK: and :X: 
and added a note

- For package, module or type names with an initial acronym  
  write the acronym in uppercase then use titlecase
  - :ok:  CSSParser, HTMLBodyValidator
  - :x:  CSSparser, HTMLbodyValidator   
  - *note* the Praxis group would prefer the manual allow titlecase: CssParser, HtmlBodyValidator
 ------

**Comment by mkborregaard** [comment]
Great. I like the idea of mentioning that there is a community preference, also because everyone reading that advice would have his own preference, and it is nice to store the information that there has been debate about this.
