### ISSUE TITLE
tables broken in guides/ShortForms.md?

### ISSUE THREAD

**Issue by tpapp** [JuliaPraxis/Naming#5]
The content of abbreviated tables seems to render as a paragraph of flow text with `|`s in them on Github, eg [here](https://github.com/JuliaPraxis/Naming/blob/master/guides/ShortForms.md).

Looking at the source, I see

```markdown
initialize | init
evaluate  | eval
calculate | calc
 | 
positive | pos
```

are the standalone `|` separators? Perhaps Github changed their syntax?

**Comment by JeffreySarnoff** [comment]
thank you -- fixed
